### ISSUE TITLE
Desafio 2

### ISSUE THREAD

**Issue by cassiocoltri** [digitalinnovationone/ganhando_produtividade_com_Stream_API_Java#15]
Boa noite Camila, tudo bem? Estou com dificuldade para resolver o exercício nº 2 (Soma dos pares)

```
List<Integer> numeros = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5, 4, 3);
		Function<Integer, Integer> somaPar = n -> n+=(n % 2);
		List<Integer> somaNumerosPares = numeros.stream().map(somaPar).toList();
		somaNumerosPares.forEach(System.out::print);
```
Gostaria de um auxílio se fosse possível, obrigado.

**Comment by cami-la** [comment]
Oi, @cassiocoltri. Tudo bem sim e por aí? (:

Então, existem várias formas de resolver esse desafio, tá? Eu faria desse jeito:

```java
        List<Integer> numeros = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5, 4, 3);

        int somaDosPares = numeros.stream()
                .filter(n -> n % 2 == 0) // Filtra apenas números pares
                .reduce(0, Integer::sum); // Reduce para calcular a soma

        System.out.println("A soma dos números pares é: " + somaDosPares);
```

Tem alguma dúvida sobre essas funções que utilizei? Se tiver, me diz que podemos ir discutindo.
Inclusive, repondi uma outra issue que explica sobre o método `reduce()`. Vê se te ajuda: https://github.com/digitalinnovationone/ganhando_produtividade_com_Stream_API_Java/issues/6#issuecomment-1701603346

**Comment by cassiocoltri** [comment]
Boa tarde Cami, entendi sim, muito obrigado pelo retorno!
Vou encerrar a issue.
Abs =D!
